version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rollersweet/wog-app
    container_name: my-wog-container
    ports:
      - "8777:80"
    volumes:
      - .:/app
    command: uvicorn MainScores:app --host 0.0.0.0 --port 80
